# frozen_string_literal: true

source 'https://rubygems.org'

gem 'erb_lint'
gem 'json'
gem 'puma', '~> 6.6'
gem 'rack'
gem 'rackup', '~> 2.2'
gem 'rubocop-fjord'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'webrick'
